version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # network_mode: "host"
    ports:
      - 8000:8000
      - 44007:44007
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/
